--- NameError.new(error_message[, name])  ruby 1.8 feature

    例外オブジェクトを生成して返します。nameは未定義だったシンボルです。

        err = NameError.new("message", "foo")
        p err
        p err.name

        # => #<NameError: message>
             "foo"

